exclude: "^$|deploy|scripts|tmp"
fail_fast: false
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: check-toml

    - repo: local
      hooks:
          - id: black
            name: formatting::black
            entry: black .
            language: system
            types: [python]
          - id: isort
            name: formatting::isort
            entry: isort
            language: system
            types: [python]

    - repo: local
      hooks:
          - id: flake8
            name: linting::flake8
            entry: flake8
            language: system
            types: [python]

    # - repo: https://github.com/PyCQA/isort
    #   rev: 5.10.1
    #   hooks:
    #     - id: isort
    #       args: ["--profile", "black", "--filter-files"]

    # - repo: https://github.com/psf/black
    #   rev: 22.1.0
    #   hooks:
    #     - id: black
    #       language_version: python3.9
    #       require_serial: true
    #       types: [python]

    # - repo: https://github.com/PyCQA/flake8
    #   rev: 4.0.1
    #   hooks:
    #     - id: flake8
